### ISSUE TITLE
error: { code: 400, error: 'daily-transaction-limit-exceeded' }

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/news-intelligence#35]
felipe@felipeurrego:~/news-intelligence$ npm start

	> news-intelligence@0.8.0 start /home/felipe/news-intelligence
	> node server.js

	Server running on port: 3013
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }
	error: { code: 400, error: 'daily-transaction-limit-exceeded' }

![400](https://cloud.githubusercontent.com/assets/428820/16328859/ddddd392-39a3-11e6-87ce-8ecb0846065d.png)

**Comment by germanattanasio** [comment]
if you read the README there is a disclaimer that says you need at least 10000 a day and a free key only gives you 1000
